# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'minipix_gui__v3.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1695, 777)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_image_frame1 = QtWidgets.QLabel(self.frame)
        self.label_image_frame1.setGeometry(QtCore.QRect(255, 15, 256, 256))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image_frame1.sizePolicy().hasHeightForWidth())
        self.label_image_frame1.setSizePolicy(sizePolicy)
        self.label_image_frame1.setMinimumSize(QtCore.QSize(256, 256))
        self.label_image_frame1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image_frame1.setText("")
        self.label_image_frame1.setObjectName("label_image_frame1")
        self.label_image_frame2 = QtWidgets.QLabel(self.frame)
        self.label_image_frame2.setGeometry(QtCore.QRect(255, 285, 256, 256))
        self.label_image_frame2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image_frame2.setText("")
        self.label_image_frame2.setObjectName("label_image_frame2")
        self.label_measurement_type1 = QtWidgets.QLabel(self.frame)
        self.label_measurement_type1.setGeometry(QtCore.QRect(260, 0, 55, 16))
        self.label_measurement_type1.setObjectName("label_measurement_type1")
        self.label_measurement_type2 = QtWidgets.QLabel(self.frame)
        self.label_measurement_type2.setGeometry(QtCore.QRect(260, 270, 55, 16))
        self.label_measurement_type2.setObjectName("label_measurement_type2")
        self.label_image_frame3 = QtWidgets.QLabel(self.frame)
        self.label_image_frame3.setGeometry(QtCore.QRect(515, 15, 256, 256))
        self.label_image_frame3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image_frame3.setText("")
        self.label_image_frame3.setObjectName("label_image_frame3")
        self.label_measurement_type3 = QtWidgets.QLabel(self.frame)
        self.label_measurement_type3.setGeometry(QtCore.QRect(520, 0, 55, 16))
        self.label_measurement_type3.setObjectName("label_measurement_type3")
        self.label_image_frame4 = QtWidgets.QLabel(self.frame)
        self.label_image_frame4.setGeometry(QtCore.QRect(515, 285, 256, 256))
        self.label_image_frame4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image_frame4.setText("")
        self.label_image_frame4.setObjectName("label_image_frame4")
        self.label_measurement_type4 = QtWidgets.QLabel(self.frame)
        self.label_measurement_type4.setGeometry(QtCore.QRect(520, 270, 55, 16))
        self.label_measurement_type4.setObjectName("label_measurement_type4")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(-170, 775, 55, 31))
        self.label_8.setObjectName("label_8")
        self.comboBox_image_log_scale = QtWidgets.QComboBox(self.frame)
        self.comboBox_image_log_scale.setGeometry(QtCore.QRect(410, 560, 111, 22))
        self.comboBox_image_log_scale.setObjectName("comboBox_image_log_scale")
        self.comboBox_image_log_scale.addItem("")
        self.comboBox_image_log_scale.addItem("")
        self.label_demo_mode = QtWidgets.QLabel(self.frame)
        self.label_demo_mode.setGeometry(QtCore.QRect(10, 680, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_demo_mode.setFont(font)
        self.label_demo_mode.setText("")
        self.label_demo_mode.setWordWrap(True)
        self.label_demo_mode.setObjectName("label_demo_mode")
        self.pushButton_initialise_detector = QtWidgets.QPushButton(self.frame)
        self.pushButton_initialise_detector.setGeometry(QtCore.QRect(540, 560, 110, 28))
        self.pushButton_initialise_detector.setObjectName("pushButton_initialise_detector")
        self.comboBox_image_convention = QtWidgets.QComboBox(self.frame)
        self.comboBox_image_convention.setGeometry(QtCore.QRect(260, 560, 131, 22))
        self.comboBox_image_convention.setObjectName("comboBox_image_convention")
        self.comboBox_image_convention.addItem("")
        self.comboBox_image_convention.addItem("")
        self.comboBox_image_convention.addItem("")
        self.tabWidget_main = QtWidgets.QTabWidget(self.frame)
        self.tabWidget_main.setGeometry(QtCore.QRect(0, 0, 251, 581))
        self.tabWidget_main.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget_main.setObjectName("tabWidget_main")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_acquire = QtWidgets.QPushButton(self.tab)
        self.pushButton_acquire.setGeometry(QtCore.QRect(10, 190, 131, 31))
        self.pushButton_acquire.setObjectName("pushButton_acquire")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(70, 60, 91, 16))
        self.label_3.setObjectName("label_3")
        self.spinBox_number_of_frames = QtWidgets.QSpinBox(self.tab)
        self.spinBox_number_of_frames.setGeometry(QtCore.QRect(170, 30, 41, 22))
        self.spinBox_number_of_frames.setMaximum(10000)
        self.spinBox_number_of_frames.setProperty("value", 1)
        self.spinBox_number_of_frames.setObjectName("spinBox_number_of_frames")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(160, 10, 71, 16))
        self.label_4.setObjectName("label_4")
        self.comboBox_mode_of_measurement = QtWidgets.QComboBox(self.tab)
        self.comboBox_mode_of_measurement.setGeometry(QtCore.QRect(80, 30, 81, 22))
        self.comboBox_mode_of_measurement.setObjectName("comboBox_mode_of_measurement")
        self.comboBox_mode_of_measurement.addItem("")
        self.comboBox_mode_of_measurement.addItem("")
        self.comboBox_mode_of_measurement.addItem("")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(80, 10, 51, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.label_2.setObjectName("label_2")
        self.spinBox_energy_threshold = QtWidgets.QDoubleSpinBox(self.tab)
        self.spinBox_energy_threshold.setGeometry(QtCore.QRect(80, 80, 61, 22))
        self.spinBox_energy_threshold.setProperty("value", 5.0)
        self.spinBox_energy_threshold.setObjectName("spinBox_energy_threshold")
        self.spinBox_integration_time = QtWidgets.QDoubleSpinBox(self.tab)
        self.spinBox_integration_time.setGeometry(QtCore.QRect(10, 80, 61, 22))
        self.spinBox_integration_time.setDecimals(3)
        self.spinBox_integration_time.setMaximum(10000000.0)
        self.spinBox_integration_time.setProperty("value", 0.1)
        self.spinBox_integration_time.setObjectName("spinBox_integration_time")
        self.pushButton_select_directory = QtWidgets.QPushButton(self.tab)
        self.pushButton_select_directory.setGeometry(QtCore.QRect(150, 150, 61, 28))
        self.pushButton_select_directory.setObjectName("pushButton_select_directory")
        self.pushButton_setup_acquisition = QtWidgets.QPushButton(self.tab)
        self.pushButton_setup_acquisition.setGeometry(QtCore.QRect(8, 110, 201, 28))
        self.pushButton_setup_acquisition.setObjectName("pushButton_setup_acquisition")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(17, 150, 91, 16))
        self.label_9.setObjectName("label_9")
        self.label_temperature = QtWidgets.QLabel(self.tab)
        self.label_temperature.setGeometry(QtCore.QRect(17, 170, 101, 21))
        self.label_temperature.setWordWrap(True)
        self.label_temperature.setObjectName("label_temperature")
        self.pushButton_check_temperature = QtWidgets.QPushButton(self.tab)
        self.pushButton_check_temperature.setGeometry(QtCore.QRect(60, 150, 81, 28))
        self.pushButton_check_temperature.setObjectName("pushButton_check_temperature")
        self.comboBox_type_of_measurement = QtWidgets.QComboBox(self.tab)
        self.comboBox_type_of_measurement.setGeometry(QtCore.QRect(10, 30, 61, 22))
        self.comboBox_type_of_measurement.setObjectName("comboBox_type_of_measurement")
        self.comboBox_type_of_measurement.addItem("")
        self.comboBox_type_of_measurement.addItem("")
        self.comboBox_type_of_measurement.addItem("")
        self.label_28 = QtWidgets.QLabel(self.tab)
        self.label_28.setGeometry(QtCore.QRect(10, 10, 51, 16))
        self.label_28.setObjectName("label_28")
        self.spinBox_bias_voltage = QtWidgets.QDoubleSpinBox(self.tab)
        self.spinBox_bias_voltage.setGeometry(QtCore.QRect(150, 80, 62, 22))
        self.spinBox_bias_voltage.setMaximum(200.0)
        self.spinBox_bias_voltage.setProperty("value", 200.0)
        self.spinBox_bias_voltage.setObjectName("spinBox_bias_voltage")
        self.label_34 = QtWidgets.QLabel(self.tab)
        self.label_34.setGeometry(QtCore.QRect(160, 60, 51, 16))
        self.label_34.setObjectName("label_34")
        self.tabWidget_minipix_modes = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_minipix_modes.setGeometry(QtCore.QRect(10, 230, 231, 321))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.tabWidget_minipix_modes.setFont(font)
        self.tabWidget_minipix_modes.setObjectName("tabWidget_minipix_modes")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.checkBox_save_in_hspy_format = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_save_in_hspy_format.setGeometry(QtCore.QRect(10, 270, 91, 20))
        self.checkBox_save_in_hspy_format.setObjectName("checkBox_save_in_hspy_format")
        self.label_39 = QtWidgets.QLabel(self.tab_6)
        self.label_39.setGeometry(QtCore.QRect(70, 140, 31, 16))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.tab_6)
        self.label_40.setGeometry(QtCore.QRect(70, 160, 31, 16))
        self.label_40.setObjectName("label_40")
        self.spinBox_scan_pixels_j = QtWidgets.QSpinBox(self.tab_6)
        self.spinBox_scan_pixels_j.setGeometry(QtCore.QRect(142, 107, 61, 22))
        self.spinBox_scan_pixels_j.setMinimum(1)
        self.spinBox_scan_pixels_j.setMaximum(10000)
        self.spinBox_scan_pixels_j.setProperty("value", 3)
        self.spinBox_scan_pixels_j.setObjectName("spinBox_scan_pixels_j")
        self.spinBox_scan_pixels_i = QtWidgets.QSpinBox(self.tab_6)
        self.spinBox_scan_pixels_i.setGeometry(QtCore.QRect(70, 107, 61, 22))
        self.spinBox_scan_pixels_i.setMinimum(1)
        self.spinBox_scan_pixels_i.setMaximum(100000)
        self.spinBox_scan_pixels_i.setProperty("value", 3)
        self.spinBox_scan_pixels_i.setObjectName("spinBox_scan_pixels_i")
        self.spinBox_x0 = QtWidgets.QSpinBox(self.tab_6)
        self.spinBox_x0.setGeometry(QtCore.QRect(90, 140, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_x0.setFont(font)
        self.spinBox_x0.setMaximum(5000)
        self.spinBox_x0.setObjectName("spinBox_x0")
        self.spinBox_y0 = QtWidgets.QSpinBox(self.tab_6)
        self.spinBox_y0.setGeometry(QtCore.QRect(90, 160, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_y0.setFont(font)
        self.spinBox_y0.setMaximum(5000)
        self.spinBox_y0.setObjectName("spinBox_y0")
        self.pushButton_abort_stack_collection = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_abort_stack_collection.setGeometry(QtCore.QRect(110, 220, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.pushButton_abort_stack_collection.setFont(font)
        self.pushButton_abort_stack_collection.setObjectName("pushButton_abort_stack_collection")
        self.plainTextEdit_sample_name = QtWidgets.QPlainTextEdit(self.tab_6)
        self.plainTextEdit_sample_name.setGeometry(QtCore.QRect(10, 50, 201, 31))
        self.plainTextEdit_sample_name.setObjectName("plainTextEdit_sample_name")
        self.label_6 = QtWidgets.QLabel(self.tab_6)
        self.label_6.setGeometry(QtCore.QRect(10, 100, 61, 41))
        self.label_6.setObjectName("label_6")
        self.checkBox_save_in_h5_format = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_save_in_h5_format.setGeometry(QtCore.QRect(10, 250, 81, 20))
        self.checkBox_save_in_h5_format.setObjectName("checkBox_save_in_h5_format")
        self.label_7 = QtWidgets.QLabel(self.tab_6)
        self.label_7.setGeometry(QtCore.QRect(130, 110, 20, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(self.tab_6)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 91, 16))
        self.label_5.setObjectName("label_5")
        self.pushButton_collect_stack = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_collect_stack.setGeometry(QtCore.QRect(10, 220, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_collect_stack.setFont(font)
        self.pushButton_collect_stack.setObjectName("pushButton_collect_stack")
        self.label_38 = QtWidgets.QLabel(self.tab_6)
        self.label_38.setGeometry(QtCore.QRect(10, 150, 61, 31))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.label_current_i = QtWidgets.QLabel(self.tab_6)
        self.label_current_i.setGeometry(QtCore.QRect(70, 90, 61, 16))
        self.label_current_i.setText("")
        self.label_current_i.setObjectName("label_current_i")
        self.label_current_j = QtWidgets.QLabel(self.tab_6)
        self.label_current_j.setGeometry(QtCore.QRect(140, 90, 61, 16))
        self.label_current_j.setText("")
        self.label_current_j.setObjectName("label_current_j")
        self.checkBox_plot_while_scanning = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_plot_while_scanning.setGeometry(QtCore.QRect(10, 190, 161, 20))
        self.checkBox_plot_while_scanning.setChecked(False)
        self.checkBox_plot_while_scanning.setObjectName("checkBox_plot_while_scanning")
        self.tabWidget_minipix_modes.addTab(self.tab_6, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.pushButton_save_pixels = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_save_pixels.setGeometry(QtCore.QRect(10, 130, 101, 24))
        self.pushButton_save_pixels.setObjectName("pushButton_save_pixels")
        self.pushButton_open_t3pa_file = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_open_t3pa_file.setGeometry(QtCore.QRect(10, 170, 101, 61))
        self.pushButton_open_t3pa_file.setObjectName("pushButton_open_t3pa_file")
        self.pushButton_acquire_pixels = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_acquire_pixels.setGeometry(QtCore.QRect(10, 10, 101, 101))
        self.pushButton_acquire_pixels.setObjectName("pushButton_acquire_pixels")
        self.tabWidget_minipix_modes.addTab(self.tab_8, "")
        self.pushButton_acquire_frame = QtWidgets.QPushButton(self.tab)
        self.pushButton_acquire_frame.setGeometry(QtCore.QRect(150, 180, 61, 41))
        self.pushButton_acquire_frame.setObjectName("pushButton_acquire_frame")
        self.checkBox_frame_integral = QtWidgets.QCheckBox(self.tab)
        self.checkBox_frame_integral.setGeometry(QtCore.QRect(150, 220, 71, 21))
        self.checkBox_frame_integral.setObjectName("checkBox_frame_integral")
        self.tabWidget_main.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget.setGeometry(QtCore.QRect(0, 40, 251, 461))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_37 = QtWidgets.QLabel(self.tab_4)
        self.label_37.setGeometry(QtCore.QRect(60, 122, 55, 16))
        self.label_37.setObjectName("label_37")
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setGeometry(QtCore.QRect(10, 52, 55, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_4)
        self.label_13.setGeometry(QtCore.QRect(130, 52, 61, 16))
        self.label_13.setObjectName("label_13")
        self.lineEdit_user = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_user.setGeometry(QtCore.QRect(40, 50, 81, 22))
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(10, 80, 55, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(130, 80, 55, 16))
        self.label_15.setObjectName("label_15")
        self.lineEdit_host = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_host.setGeometry(QtCore.QRect(40, 80, 81, 22))
        self.lineEdit_host.setObjectName("lineEdit_host")
        self.lineEdit_server = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_server.setGeometry(QtCore.QRect(40, 20, 181, 22))
        self.lineEdit_server.setObjectName("lineEdit_server")
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setGeometry(QtCore.QRect(10, 20, 55, 16))
        self.label_11.setObjectName("label_11")
        self.lineEdit_port = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_port.setGeometry(QtCore.QRect(180, 80, 51, 22))
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.lineEdit_password = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_password.setGeometry(QtCore.QRect(180, 50, 51, 22))
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.spinBox_CID = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox_CID.setGeometry(QtCore.QRect(90, 120, 111, 22))
        self.spinBox_CID.setMaximum(100000000)
        self.spinBox_CID.setObjectName("spinBox_CID")
        self.pushButton_open_client = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_open_client.setGeometry(QtCore.QRect(80, 210, 75, 24))
        self.pushButton_open_client.setObjectName("pushButton_open_client")
        self.checkBox_start_new = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_start_new.setGeometry(QtCore.QRect(90, 160, 81, 20))
        self.checkBox_start_new.setObjectName("checkBox_start_new")
        self.checkBox_gui = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_gui.setGeometry(QtCore.QRect(90, 180, 77, 20))
        self.checkBox_gui.setChecked(True)
        self.checkBox_gui.setObjectName("checkBox_gui")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.pushButton_update_SEM_state = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_update_SEM_state.setGeometry(QtCore.QRect(20, 250, 175, 24))
        self.pushButton_update_SEM_state.setObjectName("pushButton_update_SEM_state")
        self.label_17 = QtWidgets.QLabel(self.tab_5)
        self.label_17.setGeometry(QtCore.QRect(20, 70, 101, 21))
        self.label_17.setObjectName("label_17")
        self.label_22 = QtWidgets.QLabel(self.tab_5)
        self.label_22.setGeometry(QtCore.QRect(20, 220, 101, 16))
        self.label_22.setObjectName("label_22")
        self.doubleSpinBox_spot_size = QtWidgets.QDoubleSpinBox(self.tab_5)
        self.doubleSpinBox_spot_size.setGeometry(QtCore.QRect(115, 220, 80, 22))
        self.doubleSpinBox_spot_size.setMaximum(1000.0)
        self.doubleSpinBox_spot_size.setObjectName("doubleSpinBox_spot_size")
        self.doubleSpinBox_probe_current = QtWidgets.QDoubleSpinBox(self.tab_5)
        self.doubleSpinBox_probe_current.setGeometry(QtCore.QRect(115, 190, 80, 22))
        self.doubleSpinBox_probe_current.setObjectName("doubleSpinBox_probe_current")
        self.spinBox_magnification = QtWidgets.QSpinBox(self.tab_5)
        self.spinBox_magnification.setGeometry(QtCore.QRect(115, 40, 80, 22))
        self.spinBox_magnification.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spinBox_magnification.setMinimum(0)
        self.spinBox_magnification.setMaximum(1000000)
        self.spinBox_magnification.setObjectName("spinBox_magnification")
        self.label_19 = QtWidgets.QLabel(self.tab_5)
        self.label_19.setGeometry(QtCore.QRect(20, 130, 101, 21))
        self.label_19.setObjectName("label_19")
        self.label_16 = QtWidgets.QLabel(self.tab_5)
        self.label_16.setGeometry(QtCore.QRect(20, 40, 81, 16))
        self.label_16.setObjectName("label_16")
        self.label_18 = QtWidgets.QLabel(self.tab_5)
        self.label_18.setGeometry(QtCore.QRect(20, 100, 101, 16))
        self.label_18.setObjectName("label_18")
        self.label_21 = QtWidgets.QLabel(self.tab_5)
        self.label_21.setGeometry(QtCore.QRect(20, 190, 101, 16))
        self.label_21.setObjectName("label_21")
        self.doubleSpinBox_brightness = QtWidgets.QDoubleSpinBox(self.tab_5)
        self.doubleSpinBox_brightness.setGeometry(QtCore.QRect(115, 130, 80, 22))
        self.doubleSpinBox_brightness.setMaximum(100.0)
        self.doubleSpinBox_brightness.setObjectName("doubleSpinBox_brightness")
        self.doubleSpinBox_working_distance = QtWidgets.QDoubleSpinBox(self.tab_5)
        self.doubleSpinBox_working_distance.setGeometry(QtCore.QRect(115, 100, 80, 22))
        self.doubleSpinBox_working_distance.setObjectName("doubleSpinBox_working_distance")
        self.doubleSpinBox_contrast = QtWidgets.QDoubleSpinBox(self.tab_5)
        self.doubleSpinBox_contrast.setGeometry(QtCore.QRect(115, 160, 80, 22))
        self.doubleSpinBox_contrast.setMaximum(100.0)
        self.doubleSpinBox_contrast.setObjectName("doubleSpinBox_contrast")
        self.doubleSpinBox_high_voltage = QtWidgets.QDoubleSpinBox(self.tab_5)
        self.doubleSpinBox_high_voltage.setGeometry(QtCore.QRect(115, 70, 80, 22))
        self.doubleSpinBox_high_voltage.setMaximum(30.0)
        self.doubleSpinBox_high_voltage.setObjectName("doubleSpinBox_high_voltage")
        self.label_20 = QtWidgets.QLabel(self.tab_5)
        self.label_20.setGeometry(QtCore.QRect(20, 160, 101, 16))
        self.label_20.setObjectName("label_20")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.pushButton_move_stage = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_move_stage.setGeometry(QtCore.QRect(30, 210, 101, 31))
        self.pushButton_move_stage.setObjectName("pushButton_move_stage")
        self.label_24 = QtWidgets.QLabel(self.tab_9)
        self.label_24.setGeometry(QtCore.QRect(30, 60, 21, 16))
        self.label_24.setObjectName("label_24")
        self.label_27 = QtWidgets.QLabel(self.tab_9)
        self.label_27.setGeometry(QtCore.QRect(30, 150, 21, 16))
        self.label_27.setObjectName("label_27")
        self.doubleSpinBox_stage_z = QtWidgets.QDoubleSpinBox(self.tab_9)
        self.doubleSpinBox_stage_z.setGeometry(QtCore.QRect(45, 88, 80, 22))
        self.doubleSpinBox_stage_z.setMaximum(100000.0)
        self.doubleSpinBox_stage_z.setObjectName("doubleSpinBox_stage_z")
        self.doubleSpinBox_stage_r = QtWidgets.QDoubleSpinBox(self.tab_9)
        self.doubleSpinBox_stage_r.setGeometry(QtCore.QRect(45, 118, 80, 22))
        self.doubleSpinBox_stage_r.setMaximum(100000.0)
        self.doubleSpinBox_stage_r.setObjectName("doubleSpinBox_stage_r")
        self.doubleSpinBox_stage_t = QtWidgets.QDoubleSpinBox(self.tab_9)
        self.doubleSpinBox_stage_t.setGeometry(QtCore.QRect(45, 148, 80, 22))
        self.doubleSpinBox_stage_t.setMaximum(360.0)
        self.doubleSpinBox_stage_t.setObjectName("doubleSpinBox_stage_t")
        self.doubleSpinBox_stage_y = QtWidgets.QDoubleSpinBox(self.tab_9)
        self.doubleSpinBox_stage_y.setGeometry(QtCore.QRect(45, 58, 80, 22))
        self.doubleSpinBox_stage_y.setMaximum(100000.0)
        self.doubleSpinBox_stage_y.setObjectName("doubleSpinBox_stage_y")
        self.pushButton_read_stage_position = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_read_stage_position.setGeometry(QtCore.QRect(30, 180, 101, 24))
        self.pushButton_read_stage_position.setObjectName("pushButton_read_stage_position")
        self.label_23 = QtWidgets.QLabel(self.tab_9)
        self.label_23.setGeometry(QtCore.QRect(30, 32, 21, 16))
        self.label_23.setObjectName("label_23")
        self.label_26 = QtWidgets.QLabel(self.tab_9)
        self.label_26.setGeometry(QtCore.QRect(30, 120, 21, 16))
        self.label_26.setObjectName("label_26")
        self.doubleSpinBox_stage_x = QtWidgets.QDoubleSpinBox(self.tab_9)
        self.doubleSpinBox_stage_x.setGeometry(QtCore.QRect(45, 30, 80, 22))
        self.doubleSpinBox_stage_x.setMaximum(100000.0)
        self.doubleSpinBox_stage_x.setObjectName("doubleSpinBox_stage_x")
        self.label_25 = QtWidgets.QLabel(self.tab_9)
        self.label_25.setGeometry(QtCore.QRect(30, 90, 21, 16))
        self.label_25.setObjectName("label_25")
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.label_29 = QtWidgets.QLabel(self.tab_10)
        self.label_29.setGeometry(QtCore.QRect(10, 20, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.spinBox_height_pixels = QtWidgets.QSpinBox(self.tab_10)
        self.spinBox_height_pixels.setGeometry(QtCore.QRect(60, 70, 71, 22))
        self.spinBox_height_pixels.setMinimum(0)
        self.spinBox_height_pixels.setMaximum(200000)
        self.spinBox_height_pixels.setProperty("value", 682)
        self.spinBox_height_pixels.setObjectName("spinBox_height_pixels")
        self.label_30 = QtWidgets.QLabel(self.tab_10)
        self.label_30.setGeometry(QtCore.QRect(13, 52, 51, 16))
        self.label_30.setObjectName("label_30")
        self.spinBox_width_pixels = QtWidgets.QSpinBox(self.tab_10)
        self.spinBox_width_pixels.setGeometry(QtCore.QRect(60, 50, 71, 22))
        self.spinBox_width_pixels.setMinimum(0)
        self.spinBox_width_pixels.setMaximum(200000)
        self.spinBox_width_pixels.setProperty("value", 1024)
        self.spinBox_width_pixels.setObjectName("spinBox_width_pixels")
        self.label_31 = QtWidgets.QLabel(self.tab_10)
        self.label_31.setGeometry(QtCore.QRect(13, 72, 51, 16))
        self.label_31.setObjectName("label_31")
        self.doubleSpinBox_field_width = QtWidgets.QDoubleSpinBox(self.tab_10)
        self.doubleSpinBox_field_width.setGeometry(QtCore.QRect(60, 130, 71, 22))
        self.doubleSpinBox_field_width.setMaximum(5000.0)
        self.doubleSpinBox_field_width.setObjectName("doubleSpinBox_field_width")
        self.spinBox_average = QtWidgets.QSpinBox(self.tab_10)
        self.spinBox_average.setGeometry(QtCore.QRect(60, 110, 71, 22))
        self.spinBox_average.setMinimum(1)
        self.spinBox_average.setMaximum(8000)
        self.spinBox_average.setObjectName("spinBox_average")
        self.label_33 = QtWidgets.QLabel(self.tab_10)
        self.label_33.setGeometry(QtCore.QRect(10, 130, 51, 16))
        self.label_33.setObjectName("label_33")
        self.label_32 = QtWidgets.QLabel(self.tab_10)
        self.label_32.setGeometry(QtCore.QRect(10, 112, 51, 16))
        self.label_32.setObjectName("label_32")
        self.checkBox_beam_blank = QtWidgets.QCheckBox(self.tab_10)
        self.checkBox_beam_blank.setGeometry(QtCore.QRect(150, 50, 61, 16))
        self.checkBox_beam_blank.setObjectName("checkBox_beam_blank")
        self.checkBox_channel_2 = QtWidgets.QCheckBox(self.tab_10)
        self.checkBox_channel_2.setGeometry(QtCore.QRect(150, 90, 61, 20))
        self.checkBox_channel_2.setChecked(False)
        self.checkBox_channel_2.setObjectName("checkBox_channel_2")
        self.checkBox_channel_1 = QtWidgets.QCheckBox(self.tab_10)
        self.checkBox_channel_1.setGeometry(QtCore.QRect(150, 70, 51, 20))
        self.checkBox_channel_1.setChecked(True)
        self.checkBox_channel_1.setObjectName("checkBox_channel_1")
        self.pushButton_get_image_config = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_get_image_config.setGeometry(QtCore.QRect(20, 160, 110, 24))
        self.pushButton_get_image_config.setObjectName("pushButton_get_image_config")
        self.pushButton_set_image_config = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_set_image_config.setGeometry(QtCore.QRect(20, 180, 110, 24))
        self.pushButton_set_image_config.setObjectName("pushButton_set_image_config")
        self.pushButton_get_image = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_get_image.setGeometry(QtCore.QRect(150, 120, 71, 51))
        self.pushButton_get_image.setObjectName("pushButton_get_image")
        self.pushButton_plot_SEM_image = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_plot_SEM_image.setGeometry(QtCore.QRect(160, 179, 41, 24))
        self.pushButton_plot_SEM_image.setObjectName("pushButton_plot_SEM_image")
        self.pushButton_save_SEM_image = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_save_SEM_image.setGeometry(QtCore.QRect(150, 210, 61, 24))
        self.pushButton_save_SEM_image.setObjectName("pushButton_save_SEM_image")
        self.checkBox_save_ascii = QtWidgets.QCheckBox(self.tab_10)
        self.checkBox_save_ascii.setGeometry(QtCore.QRect(150, 231, 61, 20))
        self.checkBox_save_ascii.setObjectName("checkBox_save_ascii")
        self.pushButton_set_beam_position = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_set_beam_position.setGeometry(QtCore.QRect(160, 280, 41, 44))
        self.pushButton_set_beam_position.setObjectName("pushButton_set_beam_position")
        self.label_36 = QtWidgets.QLabel(self.tab_10)
        self.label_36.setGeometry(QtCore.QRect(40, 303, 51, 16))
        self.label_36.setObjectName("label_36")
        self.spinBox_beam_x = QtWidgets.QSpinBox(self.tab_10)
        self.spinBox_beam_x.setGeometry(QtCore.QRect(90, 281, 71, 22))
        self.spinBox_beam_x.setMaximum(3000)
        self.spinBox_beam_x.setObjectName("spinBox_beam_x")
        self.label_35 = QtWidgets.QLabel(self.tab_10)
        self.label_35.setGeometry(QtCore.QRect(40, 283, 51, 16))
        self.label_35.setObjectName("label_35")
        self.spinBox_beam_y = QtWidgets.QSpinBox(self.tab_10)
        self.spinBox_beam_y.setGeometry(QtCore.QRect(90, 301, 71, 22))
        self.spinBox_beam_y.setMaximum(3000)
        self.spinBox_beam_y.setObjectName("spinBox_beam_y")
        self.checkBox_external_scan = QtWidgets.QCheckBox(self.tab_10)
        self.checkBox_external_scan.setGeometry(QtCore.QRect(70, 370, 101, 20))
        self.checkBox_external_scan.setObjectName("checkBox_external_scan")
        self.checkBox_external_mode = QtWidgets.QCheckBox(self.tab_10)
        self.checkBox_external_mode.setGeometry(QtCore.QRect(70, 350, 111, 20))
        self.checkBox_external_mode.setObjectName("checkBox_external_mode")
        self.tabWidget.addTab(self.tab_10, "")
        self.tabWidget_main.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton_set_EBSD_detector = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_set_EBSD_detector.setGeometry(QtCore.QRect(130, 150, 101, 41))
        self.pushButton_set_EBSD_detector.setObjectName("pushButton_set_EBSD_detector")
        self.spinBox_chip_pixels_x = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_chip_pixels_x.setGeometry(QtCore.QRect(30, 38, 61, 22))
        self.spinBox_chip_pixels_x.setMaximum(5000)
        self.spinBox_chip_pixels_x.setProperty("value", 256)
        self.spinBox_chip_pixels_x.setObjectName("spinBox_chip_pixels_x")
        self.doubleSpinBox_pc_x = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_pc_x.setGeometry(QtCore.QRect(10, 75, 62, 22))
        self.doubleSpinBox_pc_x.setDecimals(3)
        self.doubleSpinBox_pc_x.setProperty("value", 0.421)
        self.doubleSpinBox_pc_x.setObjectName("doubleSpinBox_pc_x")
        self.doubleSpinBox_sample_tilt = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_sample_tilt.setGeometry(QtCore.QRect(170, 120, 61, 22))
        self.doubleSpinBox_sample_tilt.setProperty("value", 70.0)
        self.doubleSpinBox_sample_tilt.setObjectName("doubleSpinBox_sample_tilt")
        self.label_46 = QtWidgets.QLabel(self.tab_3)
        self.label_46.setGeometry(QtCore.QRect(10, 120, 31, 16))
        self.label_46.setObjectName("label_46")
        self.doubleSpinBox_pc_y = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_pc_y.setGeometry(QtCore.QRect(80, 75, 62, 22))
        self.doubleSpinBox_pc_y.setDecimals(3)
        self.doubleSpinBox_pc_y.setProperty("value", 0.779)
        self.doubleSpinBox_pc_y.setObjectName("doubleSpinBox_pc_y")
        self.label_43 = QtWidgets.QLabel(self.tab_3)
        self.label_43.setGeometry(QtCore.QRect(10, 55, 201, 20))
        self.label_43.setObjectName("label_43")
        self.label_48 = QtWidgets.QLabel(self.tab_3)
        self.label_48.setGeometry(QtCore.QRect(0, 152, 71, 16))
        self.label_48.setObjectName("label_48")
        self.label_42 = QtWidgets.QLabel(self.tab_3)
        self.label_42.setGeometry(QtCore.QRect(50, 20, 111, 16))
        self.label_42.setObjectName("label_42")
        self.spinBox_chip_pixels_y = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_chip_pixels_y.setGeometry(QtCore.QRect(120, 38, 61, 22))
        self.spinBox_chip_pixels_y.setMaximum(5000)
        self.spinBox_chip_pixels_y.setProperty("value", 256)
        self.spinBox_chip_pixels_y.setObjectName("spinBox_chip_pixels_y")
        self.doubleSpinBox_detector_pixel_size = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_detector_pixel_size.setGeometry(QtCore.QRect(80, 100, 71, 22))
        self.doubleSpinBox_detector_pixel_size.setProperty("value", 55.0)
        self.doubleSpinBox_detector_pixel_size.setObjectName("doubleSpinBox_detector_pixel_size")
        self.doubleSpinBox_pc_z = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_pc_z.setGeometry(QtCore.QRect(150, 75, 62, 22))
        self.doubleSpinBox_pc_z.setDecimals(3)
        self.doubleSpinBox_pc_z.setProperty("value", 0.505)
        self.doubleSpinBox_pc_z.setObjectName("doubleSpinBox_pc_z")
        self.doubleSpinBox_detector_tilt = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_detector_tilt.setGeometry(QtCore.QRect(30, 120, 61, 22))
        self.doubleSpinBox_detector_tilt.setProperty("value", 0.0)
        self.doubleSpinBox_detector_tilt.setObjectName("doubleSpinBox_detector_tilt")
        self.label_44 = QtWidgets.QLabel(self.tab_3)
        self.label_44.setGeometry(QtCore.QRect(150, 102, 51, 16))
        self.label_44.setObjectName("label_44")
        self.label_41 = QtWidgets.QLabel(self.tab_3)
        self.label_41.setGeometry(QtCore.QRect(100, 38, 20, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.label_47 = QtWidgets.QLabel(self.tab_3)
        self.label_47.setGeometry(QtCore.QRect(100, 124, 61, 16))
        self.label_47.setObjectName("label_47")
        self.label_45 = QtWidgets.QLabel(self.tab_3)
        self.label_45.setGeometry(QtCore.QRect(10, 102, 71, 16))
        self.label_45.setObjectName("label_45")
        self.spinBox_binning = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_binning.setGeometry(QtCore.QRect(190, 100, 41, 22))
        self.spinBox_binning.setMinimum(1)
        self.spinBox_binning.setMaximum(100000)
        self.spinBox_binning.setProperty("value", 1)
        self.spinBox_binning.setObjectName("spinBox_binning")
        self.comboBox_convention = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_convention.setGeometry(QtCore.QRect(70, 152, 61, 21))
        self.comboBox_convention.setObjectName("comboBox_convention")
        self.comboBox_convention.addItem("")
        self.comboBox_convention.addItem("")
        self.checkBox_remove_dynamic_background = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_remove_dynamic_background.setGeometry(QtCore.QRect(10, 280, 191, 20))
        self.checkBox_remove_dynamic_background.setObjectName("checkBox_remove_dynamic_background")
        self.pushButton_open_stack = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_open_stack.setGeometry(QtCore.QRect(10, 230, 131, 28))
        self.pushButton_open_stack.setObjectName("pushButton_open_stack")
        self.checkBox_remove_static_background = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_remove_static_background.setGeometry(QtCore.QRect(10, 260, 181, 20))
        self.checkBox_remove_static_background.setObjectName("checkBox_remove_static_background")
        self.pushButton_open_file = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_open_file.setGeometry(QtCore.QRect(150, 230, 81, 25))
        self.pushButton_open_file.setObjectName("pushButton_open_file")
        self.tabWidget_main.addTab(self.tab_3, "")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(0, 590, 81, 16))
        self.label_10.setObjectName("label_10")
        self.label_messages = QtWidgets.QLabel(self.frame)
        self.label_messages.setGeometry(QtCore.QRect(0, 610, 371, 61))
        self.label_messages.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_messages.setText("")
        self.label_messages.setWordWrap(True)
        self.label_messages.setObjectName("label_messages")
        self.label_image_frame_SEM = QtWidgets.QLabel(self.frame)
        self.label_image_frame_SEM.setGeometry(QtCore.QRect(775, 15, 768, 525))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image_frame_SEM.sizePolicy().hasHeightForWidth())
        self.label_image_frame_SEM.setSizePolicy(sizePolicy)
        self.label_image_frame_SEM.setMinimumSize(QtCore.QSize(256, 256))
        self.label_image_frame_SEM.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image_frame_SEM.setText("")
        self.label_image_frame_SEM.setObjectName("label_image_frame_SEM")
        self.label_measurement_type3_2 = QtWidgets.QLabel(self.frame)
        self.label_measurement_type3_2.setGeometry(QtCore.QRect(780, 0, 55, 16))
        self.label_measurement_type3_2.setObjectName("label_measurement_type3_2")
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1695, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_main.setCurrentIndex(0)
        self.tabWidget_minipix_modes.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_measurement_type1.setText(_translate("MainWindow", "TOA"))
        self.label_measurement_type2.setText(_translate("MainWindow", "TOT"))
        self.label_measurement_type3.setText(_translate("MainWindow", "Event"))
        self.label_measurement_type4.setText(_translate("MainWindow", "iTOT"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.comboBox_image_log_scale.setItemText(0, _translate("MainWindow", "Linear"))
        self.comboBox_image_log_scale.setItemText(1, _translate("MainWindow", "Logarithm"))
        self.pushButton_initialise_detector.setText(_translate("MainWindow", "Initialise detector"))
        self.comboBox_image_convention.setItemText(0, _translate("MainWindow", "Raw data"))
        self.comboBox_image_convention.setItemText(1, _translate("MainWindow", "EBSD convention"))
        self.comboBox_image_convention.setItemText(2, _translate("MainWindow", "TEM convention"))
        self.pushButton_acquire.setText(_translate("MainWindow", "Acquire"))
        self.label_3.setText(_translate("MainWindow", "Threshold keV"))
        self.label_4.setText(_translate("MainWindow", "No. frames"))
        self.comboBox_mode_of_measurement.setItemText(0, _translate("MainWindow", "TOA & TOT"))
        self.comboBox_mode_of_measurement.setItemText(1, _translate("MainWindow", "TOA"))
        self.comboBox_mode_of_measurement.setItemText(2, _translate("MainWindow", "EVENT_iTOT"))
        self.label.setText(_translate("MainWindow", "Mode"))
        self.label_2.setText(_translate("MainWindow", "Time s"))
        self.pushButton_select_directory.setText(_translate("MainWindow", "select dir"))
        self.pushButton_setup_acquisition.setText(_translate("MainWindow", "setup acquisition"))
        self.label_9.setText(_translate("MainWindow", "Temp °C"))
        self.label_temperature.setText(_translate("MainWindow", "0"))
        self.pushButton_check_temperature.setText(_translate("MainWindow", "temperature"))
        self.comboBox_type_of_measurement.setItemText(0, _translate("MainWindow", "Frames"))
        self.comboBox_type_of_measurement.setItemText(1, _translate("MainWindow", "Pixels"))
        self.comboBox_type_of_measurement.setItemText(2, _translate("MainWindow", "Test pulses"))
        self.label_28.setText(_translate("MainWindow", "Type"))
        self.label_34.setText(_translate("MainWindow", "Bias V"))
        self.checkBox_save_in_hspy_format.setText(_translate("MainWindow", "save hspy"))
        self.label_39.setText(_translate("MainWindow", "x0"))
        self.label_40.setText(_translate("MainWindow", "y0"))
        self.pushButton_abort_stack_collection.setText(_translate("MainWindow", "Abort"))
        self.plainTextEdit_sample_name.setPlainText(_translate("MainWindow", "HfLaOsF2"))
        self.label_6.setText(_translate("MainWindow", "Scan area\n"
"pixels"))
        self.checkBox_save_in_h5_format.setText(_translate("MainWindow", "save h5"))
        self.label_7.setText(_translate("MainWindow", "×"))
        self.label_5.setText(_translate("MainWindow", "Sample name:"))
        self.pushButton_collect_stack.setText(_translate("MainWindow", "collect stack"))
        self.label_38.setText(_translate("MainWindow", "Start point\n"
"pixels"))
        self.checkBox_plot_while_scanning.setText(_translate("MainWindow", "plot while scanning?"))
        self.tabWidget_minipix_modes.setTabText(self.tabWidget_minipix_modes.indexOf(self.tab_6), _translate("MainWindow", "Stack"))
        self.pushButton_save_pixels.setText(_translate("MainWindow", "Save pixels"))
        self.pushButton_open_t3pa_file.setText(_translate("MainWindow", "Open t3pa file\n"
"TOA-TOT"))
        self.pushButton_acquire_pixels.setText(_translate("MainWindow", "Acquire\n"
"pixels\n"
"TOA-TOT"))
        self.tabWidget_minipix_modes.setTabText(self.tabWidget_minipix_modes.indexOf(self.tab_8), _translate("MainWindow", "Pixels"))
        self.pushButton_acquire_frame.setText(_translate("MainWindow", "Get\n"
"frame"))
        self.checkBox_frame_integral.setText(_translate("MainWindow", "integral"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab), _translate("MainWindow", "Minipix"))
        self.label_37.setText(_translate("MainWindow", "CID"))
        self.label_12.setText(_translate("MainWindow", "User"))
        self.label_13.setText(_translate("MainWindow", "Password"))
        self.lineEdit_user.setText(_translate("MainWindow", "edx"))
        self.label_14.setText(_translate("MainWindow", "Host"))
        self.label_15.setText(_translate("MainWindow", "Port"))
        self.lineEdit_host.setText(_translate("MainWindow", "127.0.0.1"))
        self.label_11.setText(_translate("MainWindow", "Server"))
        self.lineEdit_port.setText(_translate("MainWindow", "0"))
        self.lineEdit_password.setText(_translate("MainWindow", "edx"))
        self.pushButton_open_client.setText(_translate("MainWindow", "Open client"))
        self.checkBox_start_new.setText(_translate("MainWindow", "Start new"))
        self.checkBox_gui.setText(_translate("MainWindow", "GUI"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Connect"))
        self.pushButton_update_SEM_state.setText(_translate("MainWindow", "Update values"))
        self.label_17.setText(_translate("MainWindow", "High voltage, kV"))
        self.label_22.setText(_translate("MainWindow", "Spot size"))
        self.label_19.setText(_translate("MainWindow", "Brightness %"))
        self.label_16.setText(_translate("MainWindow", "Magnification"))
        self.label_18.setText(_translate("MainWindow", "WD, mm"))
        self.label_21.setText(_translate("MainWindow", "Probe current nA"))
        self.label_20.setText(_translate("MainWindow", "Contrast %"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "State"))
        self.pushButton_move_stage.setText(_translate("MainWindow", "Move to position"))
        self.label_24.setText(_translate("MainWindow", "Y"))
        self.label_27.setText(_translate("MainWindow", "T"))
        self.pushButton_read_stage_position.setText(_translate("MainWindow", "Get position"))
        self.label_23.setText(_translate("MainWindow", "X"))
        self.label_26.setText(_translate("MainWindow", "R"))
        self.label_25.setText(_translate("MainWindow", "Z"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "Stage"))
        self.label_29.setText(_translate("MainWindow", "SEM  imaging"))
        self.label_30.setText(_translate("MainWindow", "Width"))
        self.label_31.setText(_translate("MainWindow", "Height"))
        self.label_33.setText(_translate("MainWindow", "Field W"))
        self.label_32.setText(_translate("MainWindow", "Average"))
        self.checkBox_beam_blank.setText(_translate("MainWindow", "Blank"))
        self.checkBox_channel_2.setText(_translate("MainWindow", "Ch2"))
        self.checkBox_channel_1.setText(_translate("MainWindow", "Ch1"))
        self.pushButton_get_image_config.setText(_translate("MainWindow", "Get image config"))
        self.pushButton_set_image_config.setText(_translate("MainWindow", "Set image config"))
        self.pushButton_get_image.setText(_translate("MainWindow", "Get image"))
        self.pushButton_plot_SEM_image.setText(_translate("MainWindow", "Plot"))
        self.pushButton_save_SEM_image.setText(_translate("MainWindow", "Save"))
        self.checkBox_save_ascii.setText(_translate("MainWindow", "ASCII"))
        self.pushButton_set_beam_position.setText(_translate("MainWindow", "Set"))
        self.label_36.setText(_translate("MainWindow", "beam y:"))
        self.label_35.setText(_translate("MainWindow", "beam x:"))
        self.checkBox_external_scan.setText(_translate("MainWindow", "External scan"))
        self.checkBox_external_mode.setText(_translate("MainWindow", "External mode"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("MainWindow", "Imaging"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_2), _translate("MainWindow", "Bruker"))
        self.pushButton_set_EBSD_detector.setText(_translate("MainWindow", "Set EBSD\n"
"detector"))
        self.label_46.setText(_translate("MainWindow", "tilt"))
        self.label_43.setText(_translate("MainWindow", "Pattern centre (pc_x, pc_y, pc_z)"))
        self.label_48.setText(_translate("MainWindow", "convention"))
        self.label_42.setText(_translate("MainWindow", "Detector chip size"))
        self.label_44.setText(_translate("MainWindow", "Binning"))
        self.label_41.setText(_translate("MainWindow", "×"))
        self.label_47.setText(_translate("MainWindow", "sample tilt"))
        self.label_45.setText(_translate("MainWindow", "pix size um"))
        self.comboBox_convention.setItemText(0, _translate("MainWindow", "tsl"))
        self.comboBox_convention.setItemText(1, _translate("MainWindow", "bruker"))
        self.checkBox_remove_dynamic_background.setText(_translate("MainWindow", "remove dynamic background"))
        self.pushButton_open_stack.setText(_translate("MainWindow", "Open stack"))
        self.checkBox_remove_static_background.setText(_translate("MainWindow", "remove static background"))
        self.pushButton_open_file.setText(_translate("MainWindow", "Open file"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_3), _translate("MainWindow", "EBSD"))
        self.label_10.setText(_translate("MainWindow", "messages"))
        self.label_measurement_type3_2.setText(_translate("MainWindow", "SEM"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

